# Generated by Django 4.1.5 on 2023-01-06 18:30

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_bb_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Фото пользователя'),
        ),
    ]
