# Generated by Django 4.1.5 on 2023-01-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_bb_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
