# Generated by Django 4.1.5 on 2023-01-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_rubric_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Адрес'),
        ),
    ]
