# Generated by Django 4.1.5 on 2023-01-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_rubric_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='slug',
        ),
    ]
