# Generated by Django 4.1.5 on 2023-01-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_rubric_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(default='', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
